// <auto-generated />
using HeartSite.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeartSite.Migrations.TestDataBaseMigrations
{
    [DbContext(typeof(TestDataBase))]
    [Migration("20240915153544_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeartSite.TestClass.CommentTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonTestId")
                        .HasColumnType("int");

                    b.Property<string>("TextTest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonTestId");

                    b.ToTable("CommentTests");
                });

            modelBuilder.Entity("HeartSite.TestClass.PersonTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonTests");
                });

            modelBuilder.Entity("HeartSite.TestClass.CommentTest", b =>
                {
                    b.HasOne("HeartSite.TestClass.PersonTest", "PersonTest")
                        .WithMany("CommentsTests")
                        .HasForeignKey("PersonTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonTest");
                });

            modelBuilder.Entity("HeartSite.TestClass.PersonTest", b =>
                {
                    b.Navigation("CommentsTests");
                });
#pragma warning restore 612, 618
        }
    }
}
